// Generated by gencpp from file assessment_package/WeedList.msg
// DO NOT EDIT!


#ifndef ASSESSMENT_PACKAGE_MESSAGE_WEEDLIST_H
#define ASSESSMENT_PACKAGE_MESSAGE_WEEDLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float64MultiArray.h>

namespace assessment_package
{
template <class ContainerAllocator>
struct WeedList_
{
  typedef WeedList_<ContainerAllocator> Type;

  WeedList_()
    : id(0)
    , plant_type()
    , weeds()  {
    }
  WeedList_(const ContainerAllocator& _alloc)
    : id(0)
    , plant_type(_alloc)
    , weeds(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _plant_type_type;
  _plant_type_type plant_type;

   typedef  ::std_msgs::Float64MultiArray_<ContainerAllocator>  _weeds_type;
  _weeds_type weeds;





  typedef boost::shared_ptr< ::assessment_package::WeedList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assessment_package::WeedList_<ContainerAllocator> const> ConstPtr;

}; // struct WeedList_

typedef ::assessment_package::WeedList_<std::allocator<void> > WeedList;

typedef boost::shared_ptr< ::assessment_package::WeedList > WeedListPtr;
typedef boost::shared_ptr< ::assessment_package::WeedList const> WeedListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assessment_package::WeedList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assessment_package::WeedList_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace assessment_package

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'assessment_package': ['/home/computing/Thorvald/WORKSPACE/catkin_ws/src/assessment_package/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::assessment_package::WeedList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assessment_package::WeedList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assessment_package::WeedList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assessment_package::WeedList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assessment_package::WeedList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assessment_package::WeedList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assessment_package::WeedList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "588c1046d234341b634ae5542e1e9e02";
  }

  static const char* value(const ::assessment_package::WeedList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x588c1046d234341bULL;
  static const uint64_t static_value2 = 0x634ae5542e1e9e02ULL;
};

template<class ContainerAllocator>
struct DataType< ::assessment_package::WeedList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assessment_package/WeedList";
  }

  static const char* value(const ::assessment_package::WeedList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assessment_package::WeedList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n\
string plant_type\n\
std_msgs/Float64MultiArray weeds\n\
\n\
================================================================================\n\
MSG: std_msgs/Float64MultiArray\n\
# Please look at the MultiArrayLayout message definition for\n\
# documentation on all multiarrays.\n\
\n\
MultiArrayLayout  layout        # specification of data layout\n\
float64[]         data          # array of data\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/MultiArrayLayout\n\
# The multiarray declares a generic multi-dimensional array of a\n\
# particular data type.  Dimensions are ordered from outer most\n\
# to inner most.\n\
\n\
MultiArrayDimension[] dim # Array of dimension properties\n\
uint32 data_offset        # padding elements at front of data\n\
\n\
# Accessors should ALWAYS be written in terms of dimension stride\n\
# and specified outer-most dimension first.\n\
# \n\
# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n\
#\n\
# A standard, 3-channel 640x480 image with interleaved color channels\n\
# would be specified as:\n\
#\n\
# dim[0].label  = \"height\"\n\
# dim[0].size   = 480\n\
# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n\
# dim[1].label  = \"width\"\n\
# dim[1].size   = 640\n\
# dim[1].stride = 3*640 = 1920\n\
# dim[2].label  = \"channel\"\n\
# dim[2].size   = 3\n\
# dim[2].stride = 3\n\
#\n\
# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n\
\n\
================================================================================\n\
MSG: std_msgs/MultiArrayDimension\n\
string label   # label of given dimension\n\
uint32 size    # size of given dimension (in type units)\n\
uint32 stride  # stride of given dimension\n\
";
  }

  static const char* value(const ::assessment_package::WeedList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assessment_package::WeedList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.plant_type);
      stream.next(m.weeds);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WeedList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assessment_package::WeedList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assessment_package::WeedList_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "plant_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.plant_type);
    s << indent << "weeds: ";
    s << std::endl;
    Printer< ::std_msgs::Float64MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.weeds);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSESSMENT_PACKAGE_MESSAGE_WEEDLIST_H
