robot_name_1: 'thorvald_001'
robot_name_2: 'thorvald_002'
communication_topic: 'row_data'

row_details: [
{start: [-3.75, 6.5], end: [-3.75, -6.5], type: 'basil'},
{start: [-2.75, 6.5], end: [-2.75, -6.5], type: 'basil'}, 
{start: [-0.75, 6.5], end: [-0.75, -6.5], type: 'cabbage'}, 
{start: [ 0.75, 6.5], end: [ 0.25, -6.5], type: 'cabbage'}, 
{start: [ 2.15, 6.5], end: [ 2.15, -6.5], type: 'onion'}, 
{start: [ 3.75, 6.5], end: [ 3.25, -6.5], type: 'onion'}
]

sprayer_details: [
{type: 'basil', nozel_radius: 0.025 },
{type: 'cabbage', nozel_radius: 0.015 },
{type: 'onion', nozel_radius: 0.05 }
]
